name: pbllandbow
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ^3.5.4

# Dependencies
dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5 # State management
  http: ^1.1.0 # HTTP requests
  url_launcher: ^6.0.20 # Open URLs

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add asset directories
  assets:
    - assets/images/landbow.png
    - assets/images/car1.jpg
    - assets/images/car2.jpg
    - assets/images/car3.jpg
    - assets/images/car4.jpg
    - assets/images/car5.jpg
    - assets/images/recomendation2.jpg
    - assets/images/recomendation1.jpg
    - assets/images/recomendation3.jpg
    - assets/images/recomendation4.jpg
    - assets/images/recomendation5.jpg
    - assets/images/explore.jpg
    - assets/images/profil.jpg
    - assets/images/promo.jpg
    - assets/images/promo22.jpg
    - assets/images/promo33.jpg
  
    


  # Fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic
