name: pbllandbow
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ^3.5.4

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5 # State management
  http: ^1.1.0 # HTTP requests
  url_launcher: ^6.1.10 # Open URLs

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add asset directories
  assets:
    - assets/images/

  # Fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic
